dist: trusty

language: node_js

node_js:
  - "7"
  - "6"

os:
  - linux
  - osx

# We don't really need sudo, but Firefox crashes on Linux when run
# via the launcher script on the containers we get when sudo: false.
# TODO: figure out the cause of that bug and disable sudo.
sudo: false

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
